### ISSUE TITLE
use_gold = true not resulting in 100% recall 

### ISSUE THREAD

**Issue by CorbenPoot** [Filter-Bubble/e2e-Dutch#10]
When using the option use_gold=true this does result in a 100% precision but not a 100% recall? Any idea how to fix this?

**Comment by dafnevk** [comment]
That's because the length of the mentions is capped to `max_span_width`, so mentions that are longer are not considered. I ran into memory issues if I allowed arbitrarily long mentions, but in principle this could be fixed by setting the max_span_width to a higher number.
